import type { Metadata } from "next";
import {Prompt} from "next/font/google";
import "./globals.css";



const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin", "thai"], // เพิ่ม thai สำหรับภาษาไทย
  weight: ["400", "700"], // เลือกน้ำหนักที่ต้องการ
});

export const metadata: Metadata = {
  title: "Money Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${prompt.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
